name: Deploy Payments functions app to azure

on:
  [push]


env:
  PAYMENTS_FUNCTIONAPP_NAME: 'dsdd-payments-functions'
  PAYMENTS_FUNCTIONAPP_PACKAGE_PATH: 'DSDD.Automations.Payments'
  REPORTS_FUNCTIONAPP_NAME: 'dsdd-reports-functions'
  REPORTS_FUNCTIONAPP_PACKAGE_PATH: 'DSDD.Automations.Reports'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy-payments:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.PAYMENTS_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.PAYMENTS_FUNCTIONAPP_NAME }}
        package: '${{ env.PAYMENTS_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_PAYMENTS_PUBLISH_PROFILE }}

  build-and-deploy-reports:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.REPORTS_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.REPORTS_FUNCTIONAPP_NAME }}
        package: '${{ env.REPORTS_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_REPORTS_PUBLISH_PROFILE }}

