name: Deploy Reports functions app to azure

on:
  [push]

env:
  APP_NAME: 'dsdd-reports-functions'
  APP_PATH: 'DSDD.Automations.Reports'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.APP_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.APP_NAME }}
        package: '${{ env.APP_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_REPORTS_PUBLISH_PROFILE }}

